export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import '@/app/globals.css'
import RegisterModal from "@/components/Modals/RegisterModal";
import LoginModal from "@/components/Modals/LoginModal";
import ToasterProvider from "@/Providers/ToastProvider";
import { ThemeProvider } from "@/providers/Theme-Provider";
import { ModalProvider } from '@/components/Modals/ModalProvider';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          //forcedTheme="light"
          enableSystem={false}
          storageKey="smashandapass-theme"
        >
          
            <ToasterProvider />
            <RegisterModal />
            <LoginModal />
            <ModalProvider />
          
          {children}
        </ThemeProvider>
        </body>
    </html>
  )
}
