export const users = [
    {
        id: 1,
        uuid: '584699ed5e6842a614a0',
        name: 'Sir MackDaddy',
        email: 'webgoonie@gmail.com',
        emailVerified: '2017-11-05 10:19:24',
        image: "",
        hashedPassword: "",
        firstName: "",
        lastName: "",
        role: "",
        nickname: "",
        show_fullname: 1,
        zipcode: "",
        profile_blob: "",
        profile_type: "",
        profile_blob_time: "",
        show_mylocation: 1,
        country: "",
        bdaymonth: "",
        bdayday: "",
        bdayyear: "",
        ethnicity: "",
        religion: "",
        showreligion: 0,
        sex: 'straight',
        orientation: 'M',
        relstatus: 'M',
        show_relstatus: 0,
        show_orientation: 0,
        pointsvalue: 20,
        last_loggedin: '2017-11-05 10:19:24',
        aboutme: '',
        updatedAt: '2017-08-05 03:52:58',
        createdAt: '2017-11-05 10:19:24',
      },
    
]
